# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='electronics_shop.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='realised',
            field=models.BooleanField(default=False),
        ),
    ]
